import calculator
import pytest


def test_0():
	cut = calculator.Calc()
	result = 	cut.divide(1,4)
	result = 	cut.multiply(4,6)
	result = 	cut.subtract(88,134)
	result = 	cut.multiply(-4,0)
	result = 	cut.divide(2,6)
	result = 	cut.multiply(8,-3)
	result = 	cut.divide(3,6)
	result = 	cut.add(30,101)
	result = 	cut.subtract(19,91)
	result = 	cut.subtract(62,39)
	result = 	cut.add(130,26)
	result = 	cut.subtract(150,118)
	result = 	cut.subtract(61,26)
	result = 	cut.multiply(-6,4)


def test_1():
	cut = calculator.Calc()
	result = 	cut.divide(-8,3)
	result = 	cut.subtract(13,13)
	result = 	cut.add(78,8)
	result = 	cut.multiply(-7,1)
	result = 	cut.multiply(-7,-5)
	result = 	cut.multiply(-10,-10)
	result = 	cut.divide(10,-6)
	result = 	cut.multiply(8,3)
	result = 	cut.multiply(1,6)
	result = 	cut.multiply(10,1)
	result = 	cut.add(145,93)
	result = 	cut.subtract(106,6)
	result = 	cut.divide(-3,-9)
	result = 	cut.add(61,12)
	result = 	cut.subtract(102,74)
	result = 	cut.divide(-10,1)
	result = 	cut.add(15,16)
	result = 	cut.divide(-7,-7)


def test_2():
	cut = calculator.Calc()
	result = 	cut.divide(4,1)
	result = 	cut.subtract(136,26)
	result = 	cut.divide(-5,3)
	result = 	cut.multiply(1,2)
	result = 	cut.subtract(42,39)
	result = 	cut.add(86,132)
	result = 	cut.multiply(6,-10)
	result = 	cut.multiply(8,-10)
	result = 	cut.divide(6,-3)
	result = 	cut.multiply(-5,-4)
	result = 	cut.add(55,16)
	result = 	cut.multiply(-9,10)
	result = 	cut.multiply(-5,-10)
	result = 	cut.subtract(56,85)
	result = 	cut.subtract(129,71)
	result = 	cut.multiply(-6,6)
	result = 	cut.multiply(3,-6)
	result = 	cut.subtract(95,19)


def test_3():
	cut = calculator.Calc()
	result = 	cut.divide(-2,-5)
	result = 	cut.subtract(41,23)
	result = 	cut.divide(-6,-6)
	result = 	cut.subtract(20,148)
	result = 	cut.add(15,30)
	result = 	cut.divide(1,6)
	result = 	cut.add(69,77)


def test_4():
	cut = calculator.Calc()
	result = 	cut.divide(1,5)
	result = 	cut.multiply(6,-2)
	result = 	cut.subtract(113,108)
	result = 	cut.subtract(23,23)
	result = 	cut.subtract(90,58)
	result = 	cut.multiply(10,-7)
	result = 	cut.multiply(4,-4)
	result = 	cut.divide(5,8)
	result = 	cut.add(18,41)
	result = 	cut.divide(-1,2)
	result = 	cut.subtract(21,33)
	result = 	cut.add(115,10)
	result = 	cut.subtract(95,76)
	result = 	cut.multiply(-5,4)
	result = 	cut.multiply(7,5)
	result = 	cut.multiply(-7,-6)
